# Generated by Django 4.2.4 on 2023-09-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='User',
            new_name='user',
        ),
    ]
