# Generated by Django 4.2.4 on 2023-09-04 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_rename_user_employeedetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1name', models.CharField(max_length=100, null=True)),
                ('company1designation', models.CharField(max_length=200, null=True)),
                ('company1salary', models.CharField(max_length=20, null=True)),
                ('company1duration', models.CharField(max_length=20, null=True)),
                ('company2name', models.CharField(max_length=100, null=True)),
                ('company2designation', models.CharField(max_length=200, null=True)),
                ('company2salary', models.CharField(max_length=20, null=True)),
                ('company2duration', models.CharField(max_length=20, null=True)),
                ('company3name', models.CharField(max_length=100, null=True)),
                ('company3designation', models.CharField(max_length=200, null=True)),
                ('company3salary', models.CharField(max_length=20, null=True)),
                ('company3duration', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
