# Generated by Django 4.2.4 on 2023-09-04 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1name',
            new_name='coursegra',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company2name',
            new_name='coursepg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company3name',
            new_name='coursephsc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1duration',
            new_name='percentagegra',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1salary',
            new_name='percentagehsc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company2duration',
            new_name='percentagepg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company2salary',
            new_name='percentagessc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1designation',
            new_name='schoolclggra',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company2designation',
            new_name='schoolclghsc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company3designation',
            new_name='schoolclgpg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company3duration',
            new_name='yearpassinggra',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company3salary',
            new_name='yearpassinghsc',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='coursessc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='schoolclgssc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='yearpassingpg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='yearpassingssc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeExperiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1name', models.CharField(max_length=100, null=True)),
                ('company1designation', models.CharField(max_length=200, null=True)),
                ('company1salary', models.CharField(max_length=20, null=True)),
                ('company1duration', models.CharField(max_length=20, null=True)),
                ('company2name', models.CharField(max_length=100, null=True)),
                ('company2designation', models.CharField(max_length=200, null=True)),
                ('company2salary', models.CharField(max_length=20, null=True)),
                ('company2duration', models.CharField(max_length=20, null=True)),
                ('company3name', models.CharField(max_length=100, null=True)),
                ('company3designation', models.CharField(max_length=200, null=True)),
                ('company3salary', models.CharField(max_length=20, null=True)),
                ('company3duration', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
