# Generated by Django 4.2.4 on 2023-09-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_coursephsc_employeeeducation_coursehsc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='joinindate',
            new_name='joiningdate',
        ),
    ]
